name: CustomDeathMessages
version: '${project.version}'
main: org.spartandevs.customdeathmessages.CustomDeathMessages
api-version: 1.19
authors: [ Sullivan, JP ]
description: Create highly customizable death messages
website: spartandevs.org

commands:
  cdm:
    description: Add, remove, edit, disable, or list death messages.
    aliases: [ customdeathmessages, customdeathmessage, deathmessage, cdm ]

permissions:
  cdm.reload:
    description: Reload the plugin
  cdm.updates:
    description: Receive update notifications
  cdm.modify:
    description: View and modify death messages
  cdm.debug:
    description: Access to debug commands
